# Generated by Django 2.1.7 on 2019-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
